# Generated by Django 3.1.4 on 2020-12-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
