# Generated by Django 3.1.4 on 2020-12-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_auto_20201226_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='snippet', max_length=250),
        ),
    ]
