# Generated by Django 3.1.4 on 2020-12-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0021_auto_20201228_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
    ]
