# Generated by Django 3.1.4 on 2020-12-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0028_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='iam',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, default='sub admin', max_length=250, null=True),
        ),
    ]
