# Generated by Django 3.1.4 on 2021-01-01 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0030_auto_20210101_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='insragram',
            new_name='instagram',
        ),
    ]
