# Generated by Django 3.1.4 on 2021-01-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0031_auto_20210101_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
