# Generated by Django 3.1.4 on 2021-01-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0032_settings_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='name',
        ),
    ]
