# Generated by Django 3.1.4 on 2021-01-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0045_auto_20210114_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='request',
        ),
        migrations.AddField(
            model_name='authorrequest',
            name='users',
            field=models.ManyToManyField(related_name='authors', to='blogapp.Profile'),
        ),
    ]
