# Generated by Django 3.1.4 on 2021-01-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0047_auto_20210121_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippet',
        ),
    ]
